### PR TITLE
Export.zip v2

### PR DESCRIPTION
**Pull request by morganherlocker**
This PR improves export functionality.

- Fix linestring projection bugs causing incorrect street overlay and short paths
- Algorithm for handling survey distances longer than street reference distance
- Refactor units to use meters constant across the board
- Refactor zip archiving code for multi-file support
- Add images to export archive
- Support for position type features
- Support for span points

The layout for the new exports is implemented as follows:

- `export.zip`
  - `spans.geojson`
    - feature collection of linestrings from all span label features
  - `positions.geojson`
    - feature collection of points from all position label features
  - `images.geojson`
    - feature collection of points from all images
    - images with a position label feature inherit their position from parent; recorded position discarded
    - images with a span label feature use the recorded position
  - `span-points.geojson`
    - feature collection of points derived from the start and stop of all span label features
  - `span-and-position-points.geojson`
    - feature collection of points derived from the start and stop of all span label features + all position label features
  - `/images`
    - directory of images that were captured during surveys

### CODE REVIEW

**Comment by emilyeros** [comment]
there's something in this PR that broke my ability to upload mbtiles. @molliemcardle and I tried to test this together with custom data for SF Bay. We uploaded the PBF and open tiles mbtiles, restarted the simulator, and got a blank map back (positioned in the right area). 

I worked around this by switching over to the master branch, where I was able to load the SF tiles and data and re-start the simulator, getting a working version of the app with tiles. I then was able to go back to the `export-zip` branch and use it successfully - either it was using the data I'd just uploaded through the `master` branch, or else it actually had uploaded the data but restarting the simulator wasn't enough to actually restart things. That seems strange so I'll go back and try to reproduce this.

Would be helpful to have someone else try this to verify (mollie's getting errors no matter which branch she runs so she can't verify)

**Comment by emilyeros** [comment]
once I got this running with SF data, here's what I found. 

Bugs:
- contents of`images` directory are not deleted when `reset surveys` button is pressed; i still get all images that were ever uploaded.
- `images.geojson` is empty

Expected behavior confirmed:
- all 5 geojson files and the images directory were exported as a zip
- `spans.geojson` was what I expected, with all spans and associated properties showing up (except the `images` array, which we noted would be empty)
- `positions.geojson` was created but with no properties (i think this is intentional and we can work through it later)
- `spanPoints.geojson` and `spanAndPositionPoints.geojson` contained the geographic points I expected. again, position points have no properties.
- deleting features works as expected; none of the deleted test spans/positions or position points ended up in the exported data
- geometries appear where i would expect them (linear reference is converting into centered geographic linestring)

**Comment by emilyeros** [comment]
Bugs:
• contents of`images` directory are not deleted when reset surveys button is pressed; i still get all images that were ever uploaded.
• images.geojson is empty

Expected behavior confirmed:
• all 5 geojson files and the images directory were exported as a zip
• spans.geojson was what I expected, with all spans and associated properties showing up (except the images array, which we noted would be empty)
• positions.geojson was created but with no properties (i think this is intentional and we can work through it later)
• spanPoints.geojson and spanAndPositionPoints.geojson contained the geographic points I expected. again, position points have no properties.
• deleting features works as expected; none of the deleted test spans/positions or position points ended up in the exported data
• geometries appear where i would expect them (linear reference is converting into centered geographic linestring)

**Comment by morganherlocker** [comment]
### Update

> contents ofimages directory are not deleted when reset surveys button is pressed; i still get all images that were ever uploaded.

This is now implemented and I have tested on my device.

I also added a fix to support miscellaneous image formats. I tried to upload a png and noticed it was saved as a jpg, causing a corrupt file. The server now reads the extension from the original image before generating a new name and uses that extension. This means that any arbitrary image format is supported, if the surveyed device supports it.

**Comment by emilyeros** [comment]
just tested this on the simulator; can confirm that previous images were deleted upon pushing the "reset" button

**Comment by morganherlocker** [comment]
> images.geojson is empty

This is now also fixed. Images has a url property and the geometry is either projected, in the case of span images, or inherited from parent, in the case of position features.

**Pull request merged**
