### PR TITLE
handle image uploads

### PR DESCRIPTION
**Pull request by peterqliu**

### CODE REVIEW

**Comment by emilyeros** [comment]
just tested this. looking at the output geojson, it looks like the content is there, but there's some character formatting that looks odd:

Screen Shot 2020-06-03 at 4 15 48 PM

see the 'images' property. are the `/"` characters a formatting bug, or intentional?

side note: there's a bunch of work that @morganherlocker has done in the `export-zip` branch/PR that hasn't been merged into `master`, so it's not included here. but it means that we are exporting a series of geojsons instead of just one. not sure if your PR will carry over to the other geojsons automatically or if these changes to handle image uploads will need to be added to the newer code, as well.

**Comment by peterqliu** [comment]
>some character formatting that looks odd

hmm I can't reproduce the backslashes. they're typically escape characters to denote a special 
character. @morganherlocker are you seeing this?

>not sure if your PR will carry over to the other geojsons automatically or if these changes to handle image uploads will need to be added to the newer code, as well.

currently the app uploads a single JSON of the curb survey. happy to tweak this as needed

**Comment by emilyeros** [comment]
> currently the app uploads a single JSON of the curb survey. happy to tweak this as needed

@morganherlocker put out a PR last week that makes the "export" button on the admin interface export a zipped collection of geojsons + an images directory. does this mean your change overrides that? or do these things just need to get integrated together, so that we get the full data dump that morgan created, but with a populated `images` property and populated `images.geojson` export file?

**Comment by emilyeros** [comment]
just going to flag this for @morganherlocker to take a look at, to make sure it integrates with the export function/formats

**Comment by morganherlocker** [comment]
Images are showing escape sequences because this is nested JSON stored as a string. This is a workaround that allows this data to be opened in an old school GIS app.

**Comment by emilyeros** [comment]
@morganherlocker ohhhh thanks for the explanation!

**Pull request merged**
